### ISSUE TITLE
Some further advice on using treeclimbR

### ISSUE THREAD

**Issue by andrewjmc** [fionarhuang/treeclimbR#15]
Well done on such a useful analysis tool! I have been dreaming of an approach like this since I started my PhD using metaproteomics and metagenomics. I have a few questions below.

I am applying treeclimbR to kraken/bracken-derived relative abundances of bacteria using the GTDB taxonomy and sequence database. I use MaAsLin to generate p values and directions at each level of the taxonomic hierarchy by iterating through the TreeSummarizedExperiment object.  I am also considering applying it to Decontam for potential contaminant identification.

GTDB has multiple advantages over the NCBI database, not least the greater proportions of reads identified. However, some genera and species of biological significance are split within the GTDB taxonomy (e.g. Genus_A, Genus_B). Of course, the underlying relationship between these genera is lost.

I could simply merge all split species and genera, however, I am more interested in the possibility of adding new levels to aggregate these split entities (as they are biologically meaningful). This would entail adding a new level between Family and Genus, and between Genus and Species. Any "unsplit" taxa would have a repeated element (e.g. Streptococcus Streptococcus pneumoniae pneumoniae), but the splits would be represented (e.g. Streptococcus Streptococcus_A pneumoniae pneumoniae_B).

My questions are:

1. How will treeclimbR cope with high levels of redundancy (e.g. most genera and species will be duplicated in the hierarchy with the exact same p values; only those who are split will have parent taxa which aggregate data)?
2. Do you know of any phylo manipulation tools which will allow me to programmatically make such changes? (if not, I will try to implement in the code which generates the Newick tree).
3. Decontam only produces p values in a single direction (as I understand it) as it compares fit of a "non-contaminant" with a "contaminant" model per taxon with small p values indicating the contaminant model fits better, and large ones indicating it doesn't. Some p values will be missing due to insufficient data. Can I expect treeclimbR also to work with one-sided hypothesis tests?

Thanks so much for advice regarding any of the above!

**Comment by fionarhuang** [comment]
Hi @andrewjmc ,

Thanks for your interest in `treeclimbR`. If I understand the idea correctly, NCBI taxonomy and GTDB taxonomy might differ. You are interested to keep those split information as Fig 2 below? 

It seems there would be a loop in the hierarchical structure in Fig. 2, and the hierarchical structure is not a tree anymore (Streptococcus_unsplit and Streptoccus_A has the same child node).  Does it make sense to have Fig.3 instead of Fig.2?

<img width="656" alt="Screenshot 2021-07-25 at 17 44 58" src="https://user-images.githubusercontent.com/22393299/126905112-4fc9a19a-b313-4b1d-b92a-13dc39c17828.png">



<img width="344" alt="Screenshot 2021-07-25 at 17 36 32" src="https://user-images.githubusercontent.com/22393299/126905192-bf55b5aa-5990-465c-93c9-317989a0565b.png">

About the questions:
1. In `treeclimbR`, when a parent node (having only one child node) and its child node have exactly the same p value, and both nodes are identified to have signal, then the parent node is taken. 
2. I guess what needs here is to convert a taxonomic table (in data frame) into a `phylo` tree?  Maybe two functions  [`toTree`](https://github.com/fionarhuang/TreeSummarizedExperiment/blob/master/R/tree_toTree.R) and  [`asPhylo`](https://github.com/fionarhuang/TreeSummarizedExperiment/blob/master/R/tree_asPhylo.R) in R package [`TreeSummarizedExperiment`](https://bioconductor.org/packages/release/bioc/html/TreeSummarizedExperiment.html) that convert a data frame to a `phylo` object. Or [`treeio`](http://bioconductor.riken.jp/packages/3.7/bioc/vignettes/treeio/inst/doc/Importer.html) if the input data is in other format.
3. Unfortunately, I am afraid that`treeclimbR` might lose control of FDR in the single direction use case. 



Ruizhu

**Comment by andrewjmc** [comment]
Thanks Ruizhu. I have settled on two approaches which may complement. One is to reorganise the simple GTDB tree so all split taxa are remerged. This combines organisms in a biologically relevant way, but potentially reduces the possibility of aggregating signal at higher levels. In parallel I am running the analysis with the full GTDB phylogeny -- this should give the best opportunity to aggregate signal due to genetic similarity.

Answer 3 is helpful. So I guess to reimplement Decontam in a way compatible with treeclimbR, I would need it to generate directional p values.
