### ISSUE TITLE
Simple explanation of DS vs DA

### ISSUE THREAD

**Issue by andrewjmc** [fionarhuang/treeclimbR#16]
Hello Ruizhu,

If my understanding is correct from the methods section of the paper, the DS approach applies the same algorithm as the DA approach but to multiple sets of p values/directions (for distinct features). There is some indication of a difference but I don't understand it. Can a different t be selected for each feature, or is a single t selected across all features. Also, is the FDR control applied across all features at once?

I have the potential for multiple sets of p values, due to different approaches (akin to sensitivity analyses). Unless the two approaches are equivalent, I presume I would be best to run independently.

It would be great if you could re-explain and confirm or refute my presumption!

Many thanks,

Andrew

**Comment by fionarhuang** [comment]
Hi @andrewjmc,

Sorry for the late response.

The main difference between the `DS` and the `DA` case for `treeclimbR` is in the data structure. The `DS` case has multiple features on an entity (e.g., application in scRNA-seq data where each cell subpopulation has multiple genes to perform comparison between groups), but `DA` has only one feature. The data structure  is one tree & a count table in the `DA` case, but one tree & multiple count tables in the `DS` case. In other words, for the `DS` case, we need to address the multiplicity issue caused by features in addition to entities. 

The FDR control is applied across all features at once.  The BH procedure is applied on the global candidate level where the same `t` is used for all features. As I provided in the reply to another open issue, you could find that even the same `t` is used, for different features, different levels of the tree are proposed for different features to capture the different signal patterns. (https://github.com/fionarhuang/treeclimbR/issues/18)

If you have only one feature (e.g., the counts of microbiome data) but have multiple sets of p values from different approaches, it would make more sense to me that results of different approaches are run independently if the goal is to compare performances of different methods. To control FDR, we have a specific range for `t`. The upper limit of `t` is estimated according to the average size of identified signal branches. For example, when there are clustered signals on the tree, let's say, a good method can detect the clustered patterns, but a bad method can detects only some leaves on the signal branches if methods are run separately. If you combine results of multiple methods and use the `DS` case, it is likely to underestimate the average size of signal branches. This would further lead to an underestimate of the upper range of `t`, and worse the performance of a good method.


Ruizhu

**Comment by andrewjmc** [comment]
Really helpful, thanks and I will follow your suggestion.

Best wishes,

Andrew
