### ISSUE TITLE
issue with `evalCand` function (Change in `data.table` syntax)

### ISSUE THREAD

**Issue by julien-roux** [fionarhuang/treeclimbR#17]
Due to change in the behavior of the subsetting in the `data.table` package (https://stackoverflow.com/questions/41051890/r-data-table-1-10-0-why-does-a-named-column-index-value-not-work-while-a-int ), there in an issue with the `evalCand` function 

For example, at line 237, `x[y, p_column]` needs to be changed to `x[y, ..p_column]`. Changes also have to be made at lines 249 and 277

**Comment by fionarhuang** [comment]
Thanks @julien-roux ! 

As users might also use `data.frame` for the `score_data`,  the use of `x[y, ..p_column]` might cause a new issue. So I tried to fix this bug by modifying the codes in line [115](https://github.com/fionarhuang/treeclimbR/blob/6e7d01b69ec3190db224840f3ae2598268d18f6b/R/evalCand.R#L115) & [118](https://github.com/fionarhuang/treeclimbR/blob/6e7d01b69ec3190db224840f3ae2598268d18f6b/R/evalCand.R#L118)

Hope the new version fix the issue here!


Ruizhu

**Comment by julien-roux** [comment]
Yes it did, thanks!
