### ISSUE TITLE
issue with `evalCand` function (type=`multiple`)

### ISSUE THREAD

**Issue by julien-roux** [fionarhuang/treeclimbR#18]
When applying `treeClimbR` to a scRNA-seq dataset (pseudo-bulk analysis) I realized that there is an issue with the implementation of the `evalCand` function (with option type=`multiple` and `feature_column` provided). My input was a  nested list named by genes returned by the function `getCand` (wrapped into a `mclapply` call, as described in the example [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/fionarhuang/treeclimbR_article/master/LPS/docs/index.html)).

I expected the `evalCand` function to "loop/lapply" through the features of the list and return a list as well (with for example a `level_info` data frame per feature). I looked at the code of the function and could see that this "looping" across features is not implemented at all in the function. The `level_info` data frame is showing the best node chosen across all features whihc is not what I expected.

One immediate solution would be to run the function through an `mclapply` call as I did for the `getCand` but this is problematic for the FDR correction which ought to be applied across all features.

Did I miss something?

**Comment by fionarhuang** [comment]
Hi @julien-roux @csoneson,

Sorry for the late response. Not sure if I understand the issue correctly, I don't see why we should expect the `evalCand` to loop through features instead of candidates (`DA`) or global candidates (`DS`). The work of `evalCand` corresponds to steps `d` & `e` in the [Fig 1](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02368-1/figures/1)  for the `DA` & [Supplementary Figure 1 ](https://static-content.springer.com/esm/art%3A10.1186%2Fs13059-021-02368-1/MediaObjects/13059_2021_2368_MOESM1_ESM.pdf) for `DS` case, correspondingly. So, it was designed to work on candidate levels instead of features.

To propose different candidates to capture different signal patterns for different features, we had it done in `getCand`. Below is a naive toy example that might help to clarify the idea in DS case.

Let's say we have 10 features and a tree on cell subpopulations. There are 30 samples (15 in A group & 15 in B group). Only the first five features (1-5) have signals, and different features have signal on different branches. Counts of features across subpopulations and samples are in the heatmap. 


![Screenshot 2021-09-18 at 11 23 35](https://user-images.githubusercontent.com/22393299/133884183-8dab6a6d-3eaa-42e6-90d9-3c5ec4c37728.png)


![Screenshot 2021-09-18 at 11 26 56](https://user-images.githubusercontent.com/22393299/133884206-dc4fe41c-4079-45cb-9124-e27272677302.png)
 
When `treeclimbR` was run, it could capture those signal nodes perfectly for different features.

![Screenshot 2021-09-18 at 11 32 21](https://user-images.githubusercontent.com/22393299/133884290-53ad6f6a-3e6b-4dcf-9d8c-deb78374a1e3.png)

If you look at candidates generated at the same `t` for different features, you see they are at different levels of the tree.

![Screenshot 2021-09-18 at 11 32 39](https://user-images.githubusercontent.com/22393299/133884312-0d293f91-7f6b-4cb7-baca-d18e1f8b3df1.png)

Ruizhu

**Comment by fionarhuang** [comment]
In case you are interested, files for the toy example in the DS case is available here [DS](https://htmlpreview.github.io/?https://github.com/fionarhuang/DS/blob/main/docs/DS_toy.html)  & the github [repository](https://github.com/fionarhuang/DS)

**Comment by julien-roux** [comment]
Dear Ruizhu,
Thanks for the answer and the pointer to the toy example. I probably got confused somewhere :-/
I will check with my dataset in the next few days and get back to you
Julien

**Comment by julien-roux** [comment]
I realize I never closed the issue! The toy example is nice indeed and I now realize that the main results are not to be found in the `level_info`, sorry for the confusion!
